### ISSUE TITLE
MonkeyType Badge Action

### ISSUE THREAD

**Issue by vnphanquang** [k5924/k5924#5]
Hello there, I see you've setup [monkeytype-readme](https://github.com/vnphanquang/monkeytype-readme) but the workflow has been failing: https://github.com/k5924/k5924/actions/workflows/monkeytype.yml.

The error looks like you've not setup monkeytype api key correctly. Someone just had [similar problem](https://github.com/vnphanquang/monkeytype-readme/issues/2) so I thought you should give it a check. Perhaps you forgot to activate the key in monkeytype settings.

Let me know if you need help. Happy typing, cheers.

**Comment by k5924** [comment]
I dont currently use the monkey type badge but I appreciate the headsup. If I start using the monkey type badge/github action ill definitely reach out if I need any help. Cheers
